### PR TITLE
Fix the installation for dplyr > 0.7.0

### PR DESCRIPTION
**Pull request by graipher**
In dplyr > 0.7.0 some SQL specific functions were made obsolete. They moved to dbplyr, instead.

See for example https://github.com/ropensci/ckanr/issues/90

Added dbplyr as requirement and imported the `sql_translator` function from it.
Needed to remove the `src_desc` function as export, because it seems to be no longer used and throws an error otherwise.

### CODE REVIEW

**Comment by rmatev** [comment]
Awesome, thanks. Could you also take care of `copy_env`, `all_names` and `ceply`, which were also moved to `dbplyr`? Then there are some more issues with the lazy evaluation, but let's not fix them here.

**Comment by graipher** [comment]
I will have a look at it later and include it as well.
Were these functions also just moved to `dbplyr`? Because it did not complain about them when I tried to install the package...

I agree, lazy evaluation should be done in a separate PR.

**Comment by rmatev** [comment]
I noticed these being a problem a few weeks ago. I think the install simply doesn't test anything since there are no tests :/
I can commit some proto tests and maybe we can improve from there.

**Comment by graipher** [comment]
Hm, they actually are not in `dbplyr`...

**Comment by rmatev** [comment]
They are, but are not exported, so they are accessed with `:::`.

**Comment by rmatev** [comment]
I've pushed a few updates and master should work now with the most recent versions of the rlang/dplyr/dbplyr ecosystem.

**Pull request closed without merging**
